# Generated by Django 5.2.8 on 2026-01-23 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MixBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cement_weight', models.FloatField(help_text='Weight of cement in kg', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('water_weight', models.FloatField(help_text='Weight of water in kg', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sand_weight', models.FloatField(help_text='Weight of sand in kg', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gravel_weight', models.FloatField(help_text='Weight of gravel in kg', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('wc_ratio', models.FloatField(help_text='Water to cement ratio', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='fair', help_text='Quality status of the concrete mix', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this mix batch was recorded')),
            ],
            options={
                'verbose_name': 'Mix Batch',
                'verbose_name_plural': 'Mix Batches',
                'ordering': ['-timestamp'],
            },
        ),
    ]
