# Generated by Django 5.2.8 on 2026-01-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixbatch',
            name='status',
            field=models.CharField(choices=[('too_dry', 'Too Dry'), ('acceptable', 'Acceptable'), ('too_wet', 'Too Wet')], default='fair', help_text='Quality status of the concrete mix', max_length=20),
        ),
    ]
