# Generated by Django 5.2.8 on 2026-02-26 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mixbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixbatch',
            name='moisture',
            field=models.IntegerField(default=0, help_text='Moisture level in percentage (0-100)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
